# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Tchuissi/DATA-690-WANG/blob/master/Assignement%202.ipynb
"""

#



"""# **Creation of an infinite loop**"""

l =[]    # creation of an empty list

count=0

while True:       # create an infinite loop
  
     if count==10:    # create a condition to stop the infinite loop at 10 numbers
       break
      
     num= input(f"\nplease enter an integer ({count + 1} of 10): ")    # f is for format, \n is to have a space between lines

     try:      
        num = int (num)    # the loop is valid for integer only
        l.append(num)   # append is a fonction that add a number to the list l
        count = count + 1   # incrementation of 1

     except:
        print ("\n You have entered a non-integer. Please try again.") # the loop is not valid, we use "except" to display the message

print("\n", l) # make sure to align print with l=[]



"""# **Max, Min and Range**"""

l1=sorted(l)    #fonction sorted to get the list in order
print("\nList in order", l1)

lmin= min(l1)
lmax= max (l1)

print("\nMin",lmin)

print("\nMax",lmax)

Lrange= l1[-1]-l1[0]  # As the list is in order, we can substract the last number with the first one to get the range.[0] is to call the first number, [-1] is to call the last number
print("\nRange",Lrange)

"""#**Mean, Variance and Standard Deviation**"""

lav = sum(l1)/len(l1)
print("Average:", sum(l1)/len(l1))

var= sum((xi- lav)**2 for xi in l1)/len(l1) # Creation of a for loop to sum all the number in the list. Use **2 to have the square
print("\nVariance:", var)

sd=var**0.5
print("\nStandard Deviation:", sd)  # The Standard deviation is the square root of the variance